apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: saipranithswargam/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.js"
        dest: .
  - image: saipranithswargam/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
  - image: saipranithswargam/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
  - image: saipranithswargam/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
  - image: saipranithswargam/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
  - image: saipranithswargam/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
